// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package widget

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed resources/blank.svg
var IconBlankSvgData []byte
var IconBlankSvg = &fyne.StaticResource{
	StaticName:    "resources/blank.svg",
	StaticContent: IconBlankSvgData,
}

//go:embed resources/question_mark_32.png
var IconQuestionmark32PngData []byte
var IconQuestionmark32Png = &fyne.StaticResource{
	StaticName:    "resources/question_mark_32.png",
	StaticContent: IconQuestionmark32PngData,
}
