// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package widget

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed resources/blank.svg
var iconBlankSvgData []byte
var iconBlankSvg = &fyne.StaticResource{
	StaticName:    "resources/blank.svg",
	StaticContent: iconBlankSvgData,
}

//go:embed resources/question_mark_32.png
var iconQuestionmark32PngData []byte
var iconQuestionmark32Png = &fyne.StaticResource{
	StaticName:    "resources/question_mark_32.png",
	StaticContent: iconQuestionmark32PngData,
}

//go:embed resources/restore.svg
var iconRestoreSvgData []byte
var iconRestoreSvg = &fyne.StaticResource{
	StaticName:    "resources/restore.svg",
	StaticContent: iconRestoreSvgData,
}

//go:embed resources/sort-ascending.svg
var iconSortAscendingSvgData []byte
var iconSortAscendingSvg = &fyne.StaticResource{
	StaticName:    "resources/sort-ascending.svg",
	StaticContent: iconSortAscendingSvgData,
}

//go:embed resources/sort-descending.svg
var iconSortDescendingSvgData []byte
var iconSortDescendingSvg = &fyne.StaticResource{
	StaticName:    "resources/sort-descending.svg",
	StaticContent: iconSortDescendingSvgData,
}

//go:embed resources/sort.svg
var iconSortSvgData []byte
var iconSortSvg = &fyne.StaticResource{
	StaticName:    "resources/sort.svg",
	StaticContent: iconSortSvgData,
}
